- hosts: k8s
  become: true
  tasks:
   - name: create deployment
     command: kubectl set image deployment/django-k8s-web-deployment django-k8s-web=895539560030.dkr.ecr.ap-south-1.amazonaws.com/sp-k8s:v1.BUILD