# Generated by Django 3.2.15 on 2022-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('release_date', models.IntegerField()),
                ('writer', models.CharField(max_length=100)),
                ('blog_detail', models.TextField()),
            ],
        ),
    ]
