# Generated by Django 3.2.15 on 2022-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_photo',
            field=models.ImageField(blank=True, default='media/uploads/k8s.png', null=True, upload_to='uploads/'),
        ),
    ]
