# Generated by Django 3.2.15 on 2022-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='release_date',
            field=models.CharField(max_length=15),
        ),
    ]
