# Generated by Django 3.2.15 on 2022-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
